name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@master
    - name: pwd  
      run: pwd
    - name: tree -l
      run: tree -l
    - name: git clone https://github.com/kintzhao/JobTest.git
      run: git clone https://github.com/kintzhao/JobTest.git
    - name: cd 
      run: cd JobTest && pwd && tree -l && cmake . && tree -l && make && tree -l
    - name: cd 
      run: pwd && ls -la && cd JobTest 
    - name: cd 
      run: pwd && ls -la && cd JobTest
    - name: pwd && ls
      run: pwd && ls
